from python:3.6
#COPY ./requirements.txt /app/requirements.txt
COPY requirements.txt ./requirements.txt
WORKDIR /app
RUN apt-get update
EXPOSE 8501
#RUN apt-get -y install curl
#RUN apt-get install build-essential libpoppler-cpp-dev pkg-config python3-dev -y
RUN pip install -r requirements.txt
COPY . /app
ENTRYPOINT ["streamlit", "run"]
CMD ["app.py"]
